<<<<<<< HEAD
# Generated by Django 3.2.18 on 2023-04-29 00:06
=======
# Generated by Django 3.2.18 on 2023-05-01 12:51
>>>>>>> 437e4a5589fcd7ab4f888e66b95b128929bc62b9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoiceelements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceelements',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
