version: "3.0"

services:
  django:
    build: .
    container_name: django
    command: gunicorn TestProject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - celery
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=yagona_billing_db
      - POSTGRES_USER=unicon_yagonabilling_admin
      - POSTGRES_PASSWORD=yagonabilling_admin_unicon_uz
  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data/
    expose:
      - 6379
  celery:
    build: .
    command: celery -A TestProject worker --loglevel=info # celery -A TestProject worker -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
  dsv-server-vpn-client:
    build: ./dsv-service-launcher
    container_name: dsv-server-vpn-client
    ports:
      - "9090:9090"
    volumes:
      - .:/dsv-server-vpn-client
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime:ro
      - ./dsv-service-launcher/vpn-client/client-eimzo.conf:/opt/app/vpn-client/client-eimzo.conf
      - ./dsv-service-launcher/vpn-client/client-unicon.uz.yks:/opt/app/vpn-client/client-unicon.uz.yks
      - ./dsv-service-launcher/logs:/opt/app/logs
    extra_hosts:
      - 'e-imzo.uz:127.0.0.5'
    labels:
      - "dsv-log=/opt/app/logs/dsv.log"
      - "vpn-log=/opt/app/logs/vpn.log"
  nginx:
    build: ./nginx
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/home/app/django/media
    ports:
      - "80:80"
    depends_on:
      - django
volumes:
  postgres_data:
  static_volume:
  media_volume:
  db_data:
  redis_data:
