version: "3.0"

services:
  django:
    build: .
    container_name: django
    command: bash -c "./scripts/docker-entrypoint.sh"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=yagona_billing_db
      - POSTGRES_USER=unicon_yagonabilling_admin
      - POSTGRES_PASSWORD=yagonabilling_admin_unicon_uz
  dsv-server-vpn-client:
    build: ./dsv-service-launcher
    container_name: dsv-server-vpn-client
    ports:
      - "9090:9090"
    volumes:
      - .:/dsv-server-vpn-client
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime:ro
      - ./dsv-service-launcher/vpn-client/client-eimzo.conf:/opt/app/vpn-client/client-eimzo.conf
      - ./dsv-service-launcher/vpn-client/client-unicon.uz.yks:/opt/app/vpn-client/client-unicon.uz.yks
      - ./dsv-service-launcher/logs:/opt/app/logs
    extra_hosts:
      - 'e-imzo.uz:127.0.0.5'
    labels:
      - "dsv-log=/opt/app/logs/dsv.log"
      - "vpn-log=/opt/app/logs/vpn.log"
