# Generated by Django 3.2.18 on 2023-05-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_c', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payedinformation',
            name='customer_mfo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='payedinformation',
            name='customer_tin',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
