# Generated by Django 3.2.18 on 2023-04-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_c', '0001_initial'),
    ]

    operations = [
    ]
