# Generated by Django 3.2.16 on 2023-02-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_c', '0002_nomenclature'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_code',
            field=models.IntegerField(default=1),
        ),
    ]
