# Generated by Django 3.2.18 on 2023-05-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_c', '0003_alter_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
