# Generated by Django 3.2.16 on 2023-02-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_usercontracttarifdevice_total_electricity'),
        ('one_c', '0004_alter_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_cash', models.FloatField()),
                ('payed_time', models.DateTimeField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one_c.invoice')),
            ],
        ),
    ]
