# Generated by Django 3.2.18 on 2023-02-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_c', '0005_payedinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(default='invoice', max_length=10),
            preserve_default=False,
        ),
    ]
