# Generated by Django 3.2.18 on 2023-04-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_c', '0008_auto_20230407_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='payedinformation',
            name='contract',
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract_code',
            field=models.CharField(default='E1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payedinformation',
            name='contract_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
