# Generated by Django 4.0.6 on 2022-09-29 11:43

import contracts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=contracts.models.slugify_upload)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=contracts.models.slugify_upload)),
                ('user_type', models.IntegerField(choices=[(1, 'Jismoniy'), (2, 'Yuridik'), (3, 'Yuridik va jismoniy')])),
                ('period', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
                ('need_documents', models.ManyToManyField(to='contracts.document')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
            ],
        ),
        migrations.CreateModel(
            name='UserContractTarifDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeviceCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_count', models.IntegerField()),
                ('units_count', models.IntegerField()),
                ('electricity', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.usercontracttarifdevice')),
            ],
        ),
        migrations.AddField(
            model_name='usercontracttarifdevice',
            name='devices',
            field=models.ManyToManyField(through='contracts.UserDeviceCount', to='contracts.device'),
        ),
        migrations.AddField(
            model_name='usercontracttarifdevice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.service'),
        ),
        migrations.AddField(
            model_name='usercontracttarifdevice',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.tarif'),
        ),
        migrations.CreateModel(
            name='TarifLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('updated_date', models.DateTimeField()),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.tarif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarifElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.element')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.tarif')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contracts.models.slugify_upload)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contracts.service')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=10)),
                ('client_signed_date', models.DateTimeField(auto_now_add=True)),
                ('contract_date', models.DateTimeField(blank=True)),
                ('service_type', models.CharField(max_length=50)),
                ('contract_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payed_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateTimeField()),
                ('file', models.FileField(upload_to=contracts.models.slugify_upload)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contracttype')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.service')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.status')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.tarif')),
            ],
        ),
    ]
