# Generated by Django 3.2.18 on 2023-06-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pkcs',
            name='contracts_p_contrac_e5d88f_idx',
        ),
        migrations.AddIndex(
            model_name='pkcs',
            index=models.Index(fields=['contract'], name='contracts_p_contrac_ec376d_idx'),
        ),
    ]
