# Generated by Django 3.2.18 on 2023-06-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20230608_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
