# Generated by Django 3.2.16 on 2022-12-14 12:42

import contracts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_usercontracttarifdevice_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertsummary',
            name='document',
        ),
        migrations.CreateModel(
            name='ExpertSummaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=contracts.models.slugify_upload)),
                ('client_visible', models.BooleanField(default=False)),
                ('expertsummary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.expertsummary')),
            ],
        ),
    ]
