# Generated by Django 3.2.18 on 2023-06-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='comment_data_center',
            field=models.TextField(blank=True, null=True),
        ),
    ]
