# Generated by Django 3.2.16 on 2023-02-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20221214_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='id_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
