# Generated by Django 3.2.16 on 2022-10-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_savedservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontracttarifdevice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercontracttarifdevice',
            name='rack_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
