# Generated by Django 3.2.18 on 2023-07-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_comment_data_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='prefix',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
