# Generated by Django 3.2.18 on 2023-02-21 08:07

import contracts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_id_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contracts.models.slugify_upload)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_contract_file', to='contracts.contract')),
            ],
        ),
    ]
