# Generated by Django 3.2.18 on 2023-07-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_group_slug'),
        ('contracts', '0005_auto_20230703_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_group', to='accounts.group'),
        ),
        migrations.AlterField(
            model_name='usercontracttarifdevice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
