# Generated by Django 3.2.16 on 2022-10-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20221024_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
