# Generated by Django 3.2.18 on 2023-02-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_contract_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='elements',
            field=models.ManyToManyField(to='contracts.Element'),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='TarifElement',
        ),
    ]
