# Generated by Django 3.2.16 on 2022-10-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_contract_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='client_signed_date',
        ),
        migrations.AlterField(
            model_name='contract',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
