# Generated by Django 3.2.18 on 2023-02-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20230227_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='new_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='new_cost_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
