# Generated by Django 3.2.16 on 2022-10-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20221025_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='file',
        ),
        migrations.AddField(
            model_name='contract',
            name='base64file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
