# Generated by Django 3.2.18 on 2023-02-27 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20230227_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldcontractfile',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_contract_file', to='contracts.contract'),
        ),
    ]
