# Generated by Django 3.2.16 on 2022-11-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_auto_20221031_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='hashcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
