# Generated by Django 3.2.18 on 2023-02-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_alter_oldcontractfile_contract'),
        ('contracts', '0009_auto_20230227_1647'),
    ]

    operations = [
    ]
