# Generated by Django 3.2.18 on 2023-03-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_merge_20230227_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='keyword',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
