# Generated by Django 3.2.16 on 2022-11-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contract_hashcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='hashcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
