# Generated by Django 3.2.16 on 2022-11-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_contract_hashcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='condition',
            field=models.IntegerField(default=0),
        ),
    ]
