# Generated by Django 3.2.18 on 2023-03-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_auto_20230309_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='like_preview_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
