# Generated by Django 3.2.16 on 2022-11-15 10:54

import contracts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0012_contract_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('summary', models.IntegerField(choices=[(1, 'Shartnoma imzolash maqsadga muvofiq'), (0, 'Shartnoma imzolash maqsadga muvofiq emas')])),
                ('document', models.FileField(blank=True, null=True, upload_to=contracts.models.slugify_upload)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
