# Generated by Django 3.2.18 on 2023-03-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_alter_contract_like_preview_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='like_preview_pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/Contract/pdf/'),
        ),
    ]
