# Generated by Django 3.2.16 on 2022-11-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_auto_20221115_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Contracts_Participants',
        ),
    ]
