# Generated by Django 3.2.18 on 2023-03-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_alter_contract_like_preview_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseServiceContractTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_tarif', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name_of_tarif', models.CharField(max_length=255)),
                ('is_discount', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='price_select_percentage',
            field=models.IntegerField(blank=True, choices=[(50, 50), (100, 100)], null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tarif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.tarif'),
        ),
        migrations.CreateModel(
            name='ExpertiseTarifContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContractExpertise', to='contracts.contract')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.expertiseservicecontracttarif')),
            ],
        ),
    ]
