# Generated by Django 3.2.18 on 2023-03-30 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230223_1907'),
        ('contracts', '0017_auto_20230329_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertsummary',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role'),
        ),
    ]
