# Generated by Django 3.2.16 on 2022-11-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_contract_agreement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='agreement_status',
        ),
    ]
