# Generated by Django 3.2.18 on 2023-04-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_expertsummary_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertisetarifcontract',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='expertisetarifcontract',
            name='tarif',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='price_select_percentage',
        ),
        migrations.DeleteModel(
            name='ExpertiseServiceContractTarif',
        ),
        migrations.DeleteModel(
            name='ExpertiseTarifContract',
        ),
    ]
