# Generated by Django 3.2.16 on 2022-11-16 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_remove_contract_agreement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertsummary',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
