# Generated by Django 3.2.16 on 2022-11-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_expertsummary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontracttarifdevice',
            name='connect_method',
            field=models.IntegerField(blank=True, choices=[(1, 'AK "UZTELECOM"'), (2, '"Sarkor-Telecom" MCHJ'), (3, 'ODF')], null=True),
        ),
        migrations.AddField(
            model_name='usercontracttarifdevice',
            name='odf_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
