# Generated by Django 3.2.18 on 2023-04-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_auto_20230403_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
