# Generated by Django 3.2.16 on 2023-01-02 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20221214_1742'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='rack',
            name='unit_count',
            field=models.IntegerField(default=42),
        ),
        migrations.CreateModel(
            name='DeviceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(blank=True, max_length=50, null=True)),
                ('device_number', models.CharField(blank=True, max_length=100, null=True)),
                ('electricity', models.IntegerField(blank=True, default=0, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.device')),
                ('device_publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.devicepublisher')),
            ],
        ),
        migrations.AlterField(
            model_name='unit',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.deviceunit'),
        ),
    ]
