# Generated by Django 3.2.18 on 2023-07-03 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20230703_1220'),
        ('services', '0002_alter_unit_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.internetprovider'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='provider_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.providercontract'),
        ),
    ]
