# Generated by Django 3.2.16 on 2023-01-05 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20230104_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceunit',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.rack'),
        ),
    ]
