# Generated by Django 3.2.16 on 2023-01-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_deviceunit_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
