# Generated by Django 3.2.16 on 2023-01-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20221214_1742'),
        ('services', '0006_auto_20230118_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
    ]
