# Generated by Django 3.2.16 on 2023-01-31 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_rack_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=30)),
                ('contract_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='deviceunit',
            name='provider_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.providercontract'),
        ),
    ]
