# Generated by Django 3.2.16 on 2023-02-16 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20230203_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.internetprovider'),
        ),
        migrations.AddField(
            model_name='rack',
            name='provider_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.providercontract'),
        ),
    ]
