# Generated by Django 3.2.18 on 2023-06-02 05:49

import contracts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
        ('accounts', '0022_alter_group_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationSystemVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('version_name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operation_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_system', to='vpsService.operationsystem', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VpsDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('hhd', 'hhd'), ('ssd', 'ssd')], max_length=3)),
                ('storage_disk', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('internet', models.IntegerField(blank=True, null=True)),
                ('tasix', models.IntegerField(blank=True, null=True)),
                ('operation_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vps_device_operation_system', to='vpsService.operationsystem')),
                ('operation_system_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vps_device_operation_system_version', to='vpsService.operationsystemversion')),
            ],
        ),
        migrations.CreateModel(
            name='VpsExpertSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('summary', models.IntegerField(choices=[(1, 'Shartnoma imzolash maqsadga muvofiq'), (0, 'Shartnoma imzolash maqsadga muvofiq emas')])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VpsTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('is_discount', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('vps_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vps_service_tariff', to='vpsService.vpsdevice')),
            ],
        ),
        migrations.CreateModel(
            name='VpsServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Bajarildi'), (2, 'Jarayonda'), (3, "Ko'rib chiqilmoqda"), (4, 'Yangi')], default=4)),
                ('contract_status', models.IntegerField(choices=[(1, 'Yangi'), (2, "To'lov kutilmoqda"), (3, 'Aktiv'), (4, 'Rad etilgan'), (5, 'Bekor qilingan'), (6, 'Yakunlangan')], default=1)),
                ('contract_number', models.CharField(max_length=10, unique=True)),
                ('id_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contract_cash', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payed_cash', models.DecimalField(decimal_places=2, max_digits=20)),
                ('contract_date', models.DateTimeField(blank=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('base64file', models.TextField(blank=True, null=True)),
                ('hashcode', models.CharField(blank=True, max_length=255, null=True)),
                ('like_preview_pdf', models.FileField(blank=True, null=True, upload_to='media/Contract/pdf/')),
                ('is_confirmed_contract', models.IntegerField(choices=[(1, 'WAITING'), (2, 'UNICON_CONFIRMED'), (3, 'CLIENT_CONFIRMED'), (4, 'DONE')], default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.service')),
            ],
        ),
        migrations.CreateModel(
            name='VpsPkcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkcs7', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpsService.vpsservicecontract')),
            ],
        ),
        migrations.CreateModel(
            name='VpsExpertSummaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=contracts.models.slugify_upload)),
                ('client_visible', models.BooleanField(default=False)),
                ('expertsummary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpsService.vpsexpertsummary')),
            ],
        ),
        migrations.AddField(
            model_name='vpsexpertsummary',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpsService.vpsservicecontract'),
        ),
        migrations.AddField(
            model_name='vpsexpertsummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vpsexpertsummary',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role'),
        ),
        migrations.CreateModel(
            name='VpsContracts_Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.agreementstatus')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpsService.vpsservicecontract')),
                ('participant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vps_contracts_participants', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
        ),
        migrations.CreateModel(
            name='VpsContractDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vps_contract_device', to='vpsService.vpsservicecontract')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vps_device_contract', to='vpsService.vpsdevice')),
            ],
        ),
    ]
