# Generated by Django 3.2.18 on 2023-06-15 05:29

import contracts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpsService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpsServiceContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contracts.models.slugify_upload)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vpsService.vpsservicecontract')),
            ],
        ),
    ]
