# Generated by Django 3.2.18 on 2023-06-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpsService', '0002_vpsservicecontractfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpsservicecontractfile',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
