# Generated by Django 3.2.18 on 2023-06-15 07:27

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpsService', '0003_alter_vpsservicecontractfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpsservicecontractfile',
            name='file',
            field=models.FileField(upload_to=contracts.models.slugify_upload),
        ),
    ]
