# Generated by Django 3.2.18 on 2023-06-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpsService', '0004_alter_vpsservicecontractfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpstariff',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='vpstariff',
            name='is_discount',
        ),
        migrations.RemoveField(
            model_name='vpstariff',
            name='price',
        ),
        migrations.AddField(
            model_name='vpsdevice',
            name='imut',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
