# Generated by Django 3.2.18 on 2023-06-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpsService', '0005_auto_20230616_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpsdevice',
            name='device_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='operationsystemversion',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='vpsdevice',
            name='imut',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vpsdevice',
            name='internet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vpsdevice',
            name='tasix',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
