# Generated by Django 3.2.18 on 2023-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpsService', '0006_auto_20230616_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpsdevice',
            name='imut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vpsdevice',
            name='internet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vpsdevice',
            name='tasix',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
