# Generated by Django 3.2.18 on 2023-06-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpsService', '0007_auto_20230616_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpsdevice',
            name='storage_type',
            field=models.CharField(choices=[('hdd', 'hdd'), ('ssd', 'ssd')], max_length=3),
        ),
    ]
