# Generated by Django 3.2.18 on 2023-07-07 13:28

import contracts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpsService', '0009_vpsdevice_ipv_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremadeContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contracts.models.slugify_upload)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premade_contract_file', to='vpsService.vpsservicecontract')),
            ],
        ),
    ]
