# Generated by Django 3.2.18 on 2023-07-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpsService', '0010_premadecontractfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PremadeContractFile',
            new_name='VpsPremadeContractFile',
        ),
    ]
