# Generated by Django 3.2.16 on 2022-10-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='type',
            field=models.IntegerField(choices=[(1, 'Fizik'), (2, 'Yuridik')], default=1),
            preserve_default=False,
        ),
    ]
