# Generated by Django 3.2.16 on 2023-02-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fizuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fizuser',
            name='birth_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fizuser',
            name='ctzn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fizuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fizuser',
            name='gd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fizuser',
            name='natn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fizuser',
            name='pport_expr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fizuser',
            name='pport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fizuser',
            name='pport_issue_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fizuser',
            name='ret_cd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fizuser',
            name='sess_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fizuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='birth_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='ctzn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='gd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='mid_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='mob_phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='natn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='pin',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='pport_expr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='pport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='pport_issue_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='pport_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='ret_cd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='sess_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='sur_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yuruser',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
