# Generated by Django 3.2.18 on 2023-05-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230501_1751'),
        ('accounts', '0002_rolepermission_group'),
    ]

    operations = [
    ]
