# Generated by Django 3.2.16 on 2023-02-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230221_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuruser',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
