# Generated by Django 3.2.16 on 2023-02-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_yuruser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.group'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Fizik'), (2, 'Yuridik')], null=True),
        ),
    ]
