# Generated by Django 3.2.18 on 2023-05-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20230501_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DepartamentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departament_croup', to='accounts.departament')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='croup_departament', to='accounts.group')),
            ],
        ),
        migrations.AddField(
            model_name='departament',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='accounts.group'),
        ),
    ]
