# Generated by Django 3.2.18 on 2023-05-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230504_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='group',
        ),
        migrations.AlterField(
            model_name='group',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
