# Generated by Django 3.2.18 on 2023-05-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230504_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_visible_in_front',
            field=models.BooleanField(default=False),
        ),
    ]
