# Generated by Django 3.2.16 on 2022-10-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userdata_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='type',
            field=models.IntegerField(choices=[(1, 'Fizik'), (2, 'Yuridik')], null=True),
        ),
    ]
