# Generated by Django 3.2.18 on 2023-05-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_group_is_visible_in_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='status_action',
            field=models.IntegerField(choices=[(1, 'Mijoz'), (2, 'Kutish zali'), (3, 'Xodim')], default=1),
        ),
    ]
