# Generated by Django 3.2.16 on 2022-10-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userdata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fizuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fizuser',
            name='mob_phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fizuser',
            name='tin',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
