# Generated by Django 3.2.18 on 2023-05-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userdata_status_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
