# Generated by Django 3.2.18 on 2023-05-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_group_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='filter_tag',
            field=models.IntegerField(blank=True, choices=[(1, 'Boshqaruv')], null=True),
        ),
    ]
