# Generated by Django 3.2.18 on 2023-05-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rolepermission_filter_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='filter_tag',
        ),
        migrations.AddField(
            model_name='permission',
            name='filter_tag',
            field=models.IntegerField(blank=True, choices=[(1, 'Boshqaruv')], null=True),
        ),
    ]
