# Generated by Django 3.2.18 on 2023-05-08 06:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230505_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.slugify_upload),
        ),
    ]
