# Generated by Django 3.2.16 on 2022-12-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20221201_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yuruser',
            name='ifut',
        ),
    ]
