# Generated by Django 3.2.16 on 2022-12-02 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_yuruser_ifut'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMFOName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfo', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='yuruser',
            name='mfo',
        ),
        migrations.AddField(
            model_name='yuruser',
            name='bank_mfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bankmfoname'),
        ),
    ]
