# Generated by Django 3.2.18 on 2023-05-11 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_unicondatas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUniconDatas',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mid_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sur_name', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.CharField(blank=True, max_length=50, null=True)),
                ('per_adr', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('e_xat', models.EmailField(blank=True, max_length=254, null=True)),
                ('postCode', models.CharField(blank=True, max_length=20, null=True)),
                ('tin', models.CharField(blank=True, max_length=9, null=True)),
                ('paymentAccount', models.CharField(blank=True, max_length=24, null=True)),
                ('xxtut', models.CharField(blank=True, max_length=20, null=True)),
                ('ktut', models.CharField(blank=True, max_length=20, null=True)),
                ('oked', models.CharField(blank=True, max_length=5, null=True)),
                ('web_site', models.URLField(blank=True, null=True)),
                ('dm_web_site', models.URLField(blank=True, null=True)),
                ('dm_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_mfo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.bankmfoname')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical unicon datas',
                'verbose_name_plural': 'historical unicon datass',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
