# Generated by Django 3.2.16 on 2022-12-02 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20221202_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankmfoname',
            name='name',
        ),
        migrations.AddField(
            model_name='bankmfoname',
            name='bank_name',
            field=models.CharField(default='Aloqabank', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankmfoname',
            name='branch_address',
            field=models.CharField(default="100047, Toshkent shahri, Mirobod tumani, Amir Temur shoh ko'chasi, 4 uy", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankmfoname',
            name='branch_name',
            field=models.CharField(default='AT "Aloqabank" bosh ofisi', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankmfoname',
            name='branch_sym',
            field=models.IntegerField(choices=[(0, "Markaziy bankning tarkibiy bo'linmalari"), (1, 'Tijorat banklarining bosh ofislari'), (2, "Tijorat banklarining to'lov markazlari"), (3, 'Tijorat banklarining filiallari')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankmfoname',
            name='changed_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankmfoname',
            name='city',
            field=models.CharField(default='Toshkent', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankmfoname',
            name='district',
            field=models.CharField(default='Mirobod tumani', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankmfoname',
            name='geolocation',
            field=models.CharField(default='41.309935, 69.277695', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankmfoname',
            name='opened_date',
            field=models.DateField(default='1995-03-22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankmfoname',
            name='region',
            field=models.CharField(default='Toshkent shahri', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankmfoname',
            name='tin',
            field=models.CharField(default='200829053', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankmfoname',
            name='website',
            field=models.CharField(default='www.aloqabank.uz', max_length=50),
            preserve_default=False,
        ),
    ]
