# Generated by Django 3.2.16 on 2022-12-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20221202_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankmfoname',
            name='branch_sym',
        ),
    ]
