# Generated by Django 3.2.16 on 2022-12-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_bankmfoname_branch_sym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankmfoname',
            name='changed_date',
        ),
        migrations.RemoveField(
            model_name='bankmfoname',
            name='opened_date',
        ),
    ]
