# Generated by Django 3.2.18 on 2023-05-13 10:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20230512_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.slugify_upload),
        ),
    ]
