# Generated by Django 3.2.18 on 2023-05-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_delete_historicalrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'admin'), ("departament boshlig'i", "departament boshlig'i"), ('mijoz', 'mijoz'), ("bo'lim boshlig'i", "bo'lim boshlig'i"), ("direktor o'rinbosari", "direktor o'rinbosari"), ('direktor', 'direktor'), ('iqtisodchi', 'iqtisodchi')], max_length=50),
        ),
    ]
