# Generated by Django 3.2.18 on 2023-06-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_group_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='group',
        ),
        migrations.AddField(
            model_name='userdata',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Group'),
        ),
    ]
