# Generated by Django 3.2.18 on 2023-07-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
