# Generated by Django 3.2.18 on 2023-07-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'admin'), ("departament boshlig'i", "departament boshlig'i"), ("bo'lim boshlig'i", "bo'lim boshlig'i"), ("bo'lim mutaxasisi", "bo'lim mutaxasisi"), ("direktor o'rinbosari", "direktor o'rinbosari"), ('direktor', 'direktor'), ('buxgalteriya', 'buxgalteriya'), ('yurist', 'yurist'), ('dispetcher', 'dispetcher'), ('yetakchi muhandis', 'yetakchi muhandis'), ('mijoz', 'mijoz')], max_length=50),
        ),
    ]
