# Generated by Django 3.2.18 on 2023-03-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_merge_20230227_1650'),
        ('main', '0003_alter_application_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_application', to='contracts.service'),
            preserve_default=False,
        ),
    ]
