# Generated by Django 3.2.18 on 2023-03-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_application_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(default=3, upload_to='application/files'),
            preserve_default=False,
        ),
    ]
