# Generated by Django 3.2.18 on 2023-03-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_application_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotChatIDs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=255)),
                ('chat_id', models.IntegerField()),
            ],
        ),
    ]
