# Generated by Django 3.2.18 on 2023-04-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseServiceTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_tarif', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='expertiseservicecontracttarif',
            name='title_of_tarif',
        ),
        migrations.AddField(
            model_name='expertiseservicecontracttarif',
            name='expertise_service_tarif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expertiseService.expertiseservicetarif'),
            preserve_default=False,
        ),
    ]
