# Generated by Django 3.2.18 on 2023-04-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseService', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertiseservicecontract',
            name='client',
        ),
        migrations.RemoveField(
            model_name='expertiseservicecontract',
            name='service',
        ),
        migrations.AddField(
            model_name='expertiseservicecontract',
            name='contract_status',
            field=models.IntegerField(choices=[(0, 'Yaratilgan'), (1, 'Rad etilgan'), (2, 'Yakunlangan'), (3, 'Aktiv'), (4, "To'lov kutilmoqda"), (5, 'Bekor qilingan'), (6, 'Yangi')], default=0),
        ),
        migrations.AddField(
            model_name='expertiseservicecontract',
            name='status',
            field=models.IntegerField(choices=[(1, 'Bajarildi'), (2, 'Jarayonda'), (3, "Ko'rib chiqilmoqda"), (4, 'Yangi')], default=4),
        ),
    ]
