# Generated by Django 3.2.18 on 2023-04-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_auto_20230403_1300'),
        ('expertiseService', '0002_auto_20230403_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertiseservicecontract',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contracts.service'),
            preserve_default=False,
        ),
    ]
