# Generated by Django 3.2.18 on 2023-04-03 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseService', '0002_auto_20230403_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertiseservicecontract',
            name='contract_status',
            field=models.IntegerField(choices=[(0, 'Yaratilgan'), (1, 'Rad etilgan'), (2, 'Yakunlangan'), (3, 'Aktiv'), (4, "To'lov kutilmoqda"), (5, 'Bekor qilingan'), (6, 'Yangi')], default=0, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
    ]
