# Generated by Django 3.2.18 on 2023-05-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseService', '0003_expertiseservicecontract_is_confirmed_contract_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertiseservicecontract',
            name='contract_status',
            field=models.IntegerField(choices=[(0, 'Yaratilgan'), (1, 'Rad etilgan'), (2, 'Yakunlangan'), (3, 'Aktiv'), (4, "To'lov kutilmoqda"), (5, 'Bekor qilingan'), (6, 'Yangi'), (7, 'Tasdiqlangan')], default=0),
        ),
    ]
