# Generated by Django 3.2.18 on 2023-04-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseService', '0003_auto_20230418_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertiseservicecontracttarif',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
