# Generated by Django 3.2.18 on 2023-04-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseService', '0004_alter_expertiseservicecontracttarif_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpertiseServiceTarif',
            new_name='ExpertiseTarif',
        ),
    ]
