# Generated by Django 3.2.18 on 2023-04-03 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseService', '0004_alter_expertiseservicecontract_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertiseservicecontract',
            name='status',
            field=models.IntegerField(choices=[(1, 'Bajarildi'), (2, 'Jarayonda'), (3, "Ko'rib chiqilmoqda"), (4, 'Yangi')], validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
