# Generated by Django 3.2.18 on 2023-05-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseService', '0004_alter_expertiseservicecontract_contract_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertiseservicecontract',
            name='is_confirmed_contract_client',
        ),
        migrations.AddField(
            model_name='expertiseservicecontract',
            name='is_confirmed_contract',
            field=models.IntegerField(choices=[(1, 'WAITING'), (2, 'UNICON_CONFIRMED'), (3, 'CLIENT_CONFIRMED')], default=1),
        ),
    ]
