# Generated by Django 3.2.18 on 2023-04-04 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expertiseService', '0004_expertiseservicecontract_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertisecontracts_participants',
            name='participant_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participant_user', to='accounts.userdata'),
            preserve_default=False,
        ),
    ]
