# Generated by Django 3.2.18 on 2023-05-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseService', '0005_auto_20230520_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertiseservicecontract',
            name='contract_status',
            field=models.IntegerField(choices=[(1, 'Yangi'), (2, 'Mijoz imzolashi kutilmoqda'), (3, "To'lov kutilmoqda"), (4, 'Aktiv'), (5, 'Rad etilgan'), (6, 'Bekor qilingan'), (7, 'Yakunlangan')], default=0),
        ),
    ]
