# Generated by Django 3.2.18 on 2023-04-18 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseService', '0005_rename_expertiseservicetarif_expertisetarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertiseservicecontracttarif',
            name='expertise_service_tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_service_tarif', to='expertiseService.expertisetarif'),
        ),
    ]
