# Generated by Django 3.2.18 on 2023-04-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseService', '0005_expertisecontracts_participants_participant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertiseservicecontract',
            name='id_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
